* LSTM to Solve the Time Dependent Schrödinger Equation
Autor: Jessica Martínez Marcelo

Esta tesis fue basada en el formato: [[https://bitbucket.org/amiede/classicthesis/wiki/Home][classicthesis]], desarrollado por /André Miede/.

Mis pequeñas aportaciones:
- Idioma español
- Nuevo formato de portada
- Cambio en el estilo de los capítulos, tablas, decoraciones

** Requerimentos:
- Compilador xelatex
- Fuente: Tex Gyre
 - Latex version info:
   pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
** Para correr correctamente:
- ~$ bibtex tesis.aux~ 
** Notas

